name: Build OS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Install deps
        run: bash install-deps.sh

      - name: Start building OS
        run: sudo ./build.sh
